DROP TABLE IF EXISTS CRYPTOASSET;
 
CREATE TABLE CRYPTOASSET (
  symbol VARCHAR(100) PRIMARY KEY,
  total DECIMAL(5,2) DEFAULT 0 NOT NULL);

insert into CRYPTOASSET (symbol, total) values ('BTC', 0.5);